### ISSUE TITLE
error on database acquisition at eventupdate

### ISSUE THREAD

**Issue by himorin** [himorin/pfs_notice#3]
% ./eventupdate.py --noauth_local_webserver
Traceback (most recent call last):
  File "./eventupdate.py", line 86, in <module>
    notices = dbh.ListNoticesBySource(event['icaluid'])
  File "/data1/landfill/http/pfs_notice/eventupdate/EventDB.py", line 55, in ListNoticesBySource
    [source])
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 559, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 494, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 396, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'source' in 'where clause'

**Comment by himorin** [comment]
it's not a forgotten handler for missing column, but just an issue of SQL (specified wrong table to select).
testing fix at landfill.
